### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.cisco.nxos/pull/7
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 7e4a557f5b647680a99ba4bab46d62c8871f9395

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5d996656b4fd32700aabe6e129081d30930ca149

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 56d994d38f7727336d3f04fb763517c2dfc8c171

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now be1a024c7659ec8613d1b0b4cb0a3d8897fc9654

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now da23053859ef13db20aa1aea884bfaf8c0404afe

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2f5742c7abc412d673c12557aaee105f7e2173bc

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 9a23201f99621f05ba406e460e1093ec3e27ba34

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2ffacce5035c147b446a5fe77df2bcc6ff7ae3bb

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now bc26fd6f0a5b74456ca560dcee1c7aeaef282edf

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 679b55c287cc5ceca0e4328c852eb3bd28a7ff9d

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
